name: Build & test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
    defaults:
      run:
        working-directory: csv-combiner
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Turn on 'editable' mode
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pytest
